#################################
# è¯­è¨€é…ç½®ï¼Œè¿™é‡Œæˆ‘ä¸æ˜¯ç”¨æ¥é…ç½®è¯­è¨€ #
#################################

[en]
languageName = "English"
weight = 1

[en.profileMode]
  enabled = true
  title = "00000000!!!"
  subtitle = "ğŸ˜€ğŸ˜ƒğŸ˜„ğŸ˜ğŸ˜†ğŸ˜…ğŸ¤£ğŸ˜‚ğŸ™‚ğŸ™ƒğŸ˜‰ğŸ˜ŠğŸ˜‡ğŸ¥°ğŸ˜ğŸ¤©ğŸ˜˜ğŸ˜—ğŸ˜šğŸ˜™ğŸ˜‹ğŸ˜›ğŸ˜œğŸ¤ªğŸ˜ğŸ¤‘ğŸ¤—ğŸ¤­ğŸ¤«ğŸ¤”ğŸ¤ğŸ¤¨ğŸ˜ğŸ˜‘ğŸ˜¶ğŸ˜¶â€ğŸŒ«ï¸ğŸ˜ğŸ˜’ğŸ™„ğŸ˜¬ğŸ˜®â€ğŸ’¨ğŸ¤¥ğŸ˜ŒğŸ˜”ğŸ˜ªğŸ¤¤ğŸ˜´ğŸ˜·ğŸ¤’ğŸ¤•ğŸ¤¢ğŸ¤®ğŸ¤§ğŸ¥µğŸ¥¶ğŸ¥´ğŸ˜µğŸ˜µâ€ğŸ’«ğŸ¤¯ğŸ¤ ğŸ¥³ğŸ˜ğŸ¤“ğŸ§ğŸ˜•ğŸ˜ŸğŸ™â˜¹ï¸ğŸ˜®ğŸ˜¯ğŸ˜²ğŸ˜³ğŸ¥ºğŸ˜¦ğŸ˜§ğŸ˜¨ğŸ˜°ğŸ˜¥ğŸ˜¢ğŸ˜­ğŸ˜±ğŸ˜–ğŸ˜£ğŸ˜ğŸ˜“ğŸ˜©ğŸ˜«ğŸ¥±ğŸ˜¤ğŸ˜¡ğŸ˜ ğŸ¤¬ğŸ˜ˆğŸ‘¿ğŸ’€â˜ ï¸ğŸ’©ğŸ¤¡ğŸ‘¹ğŸ‘ºğŸ‘»ğŸ‘½ğŸ‘¾ğŸ¤–ğŸ˜ºğŸ˜¸ğŸ˜¹ğŸ˜»ğŸ˜¼ğŸ˜½ğŸ™€ğŸ˜¿ğŸ˜¾"
  imageUrl = "/images/site/avatar.jpg"
  imageTitle = "Linlccc"
  # imageWidth = 120
  # imageHeight = 120

[[en.menu.main]]
  name = 'Posts'
  url = '/posts'
  weight = 1

[[en.profileMode.buttons]]
  name = 'Posts'
  url = 'posts'


[zh]
languageName = "ä¸­æ–‡"
weight = 1
