#################################
# è¯­è¨€é…ç½®ï¼Œè¿™é‡Œæˆ‘ä¸æ˜¯ç”¨æ¥é…ç½®è¯­è¨€ #
#################################

[en]
languageName = "English"
weight = 1
# languagedirection = 'rtl'

[en.Params]
CanonicalLinkText = 'Originally published at'

# è‹±æ–‡å•ç‹¬è®¾ç½®profileMode
[en.Params.profileMode]
enabled = true
title = "00000000!!!"
# subtitle = "ğŸ˜€ğŸ˜ƒğŸ˜„ğŸ˜ğŸ˜†ğŸ˜…ğŸ¤£ğŸ˜‚ğŸ™‚ğŸ™ƒğŸ˜‰ğŸ˜ŠğŸ˜‡ğŸ¥°ğŸ˜ğŸ¤©ğŸ˜˜ğŸ˜—ğŸ˜šğŸ˜™ğŸ˜‹ğŸ˜›ğŸ˜œğŸ¤ªğŸ˜ğŸ¤‘ğŸ¤—ğŸ¤­ğŸ¤«ğŸ¤”ğŸ¤ğŸ¤¨ğŸ˜ğŸ˜‘ğŸ˜¶ğŸ˜¶â€ğŸŒ«ï¸ğŸ˜ğŸ˜’ğŸ™„ğŸ˜¬ğŸ˜®â€ğŸ’¨ğŸ¤¥ğŸ˜ŒğŸ˜”ğŸ˜ªğŸ¤¤ğŸ˜´ğŸ˜·ğŸ¤’ğŸ¤•ğŸ¤¢ğŸ¤®ğŸ¤§ğŸ¥µğŸ¥¶ğŸ¥´ğŸ˜µğŸ˜µâ€ğŸ’«ğŸ¤¯ğŸ¤ ğŸ¥³ğŸ˜ğŸ¤“ğŸ§ğŸ˜•ğŸ˜ŸğŸ™â˜¹ï¸ğŸ˜®ğŸ˜¯ğŸ˜²ğŸ˜³ğŸ¥ºğŸ˜¦ğŸ˜§ğŸ˜¨ğŸ˜°ğŸ˜¥ğŸ˜¢ğŸ˜­ğŸ˜±ğŸ˜–ğŸ˜£ğŸ˜ğŸ˜“ğŸ˜©ğŸ˜«ğŸ¥±ğŸ˜¤ğŸ˜¡ğŸ˜ ğŸ¤¬ğŸ˜ˆğŸ‘¿ğŸ’€â˜ ï¸ğŸ’©ğŸ¤¡ğŸ‘¹ğŸ‘ºğŸ‘»ğŸ‘½ğŸ‘¾ğŸ¤–ğŸ˜ºğŸ˜¸ğŸ˜¹ğŸ˜»ğŸ˜¼ğŸ˜½ğŸ™€ğŸ˜¿ğŸ˜¾"
# imageUrl = "/images/site/icon192.png"
# imageTitle = "Linlccc"
# imageWidth = 120
# imageHeight = 120

[[en.Params.profileMode.buttons]]
name = 'Search'
url = 'search'

[[en.Params.profileMode.buttons]]
name = 'Posts'
url = 'posts'

[[en.Params.profileMode.buttons]]
name = 'Tags'
url = 'tags'

[[en.Params.profileMode.buttons]]
name = 'Archives'
url = 'archives'


[zh]
languageName = "ä¸­æ–‡"
weight = 1
# è¯­è¨€æ–¹å‘
# languagedirection = 'rtl'
