# å‚æ•°é…ç½®

# è¿™é‡Œæ˜¯çœŸæ­£ä¼šç”¨åˆ°çš„å‚æ•°ï¼Œå¯¹å‚æ•°é‡å†™
#################################

### é¢å‘æ•´ä¸ªç«™ç‚¹çš„é…ç½® ###
# æè¿°
description: ä¸å¦‚æ‘¸é±¼ï¼ï¼ï¼
# é»˜è®¤ä¸»é¢˜  [auto, dark, light]
defaultTheme: auto
# ç¦ç”¨ä¸»é¢˜åˆ‡æ¢
disableThemeToggle: false
# ç¦ç”¨æ»šåŠ¨åˆ°é¡¶éƒ¨
disableGoToTop: false
# æ˜¯å¦å¯ç”¨ manifest (å®‰è£…åˆ°æ¡Œé¢)
isEnableManifest: true
# å¤šè¯­è¨€åˆ‡æ¢æ˜¾ç¤ºå®Œæ•´è¯­è¨€åç§°
displayFullLangName: false
# åˆ—è¡¨é¡µä¸­æ˜¾ç¤º Rss æŒ‰é’®
showRssButtonInSectionTermList: true
# Rss æ˜¾ç¤ºå…¨éƒ¨å†…å®¹
showFullTextinRSS: false
# css é…ç½®
css:
  # æ˜¯å¦æŒ‰éœ€å¼•å…¥ css
  isImportDemand: false

# ç½‘ç«™å›¾æ ‡
favicon:
  dark:
    favicon: /favicon/dark/favicon.ico
    icon: /favicon/dark/favicon.svg
    favicon_16: /favicon/dark/favicon-16x16.png
    favicon_32: /favicon/dark/favicon-32x32.png
    favicon_180: /favicon/dark/favicon-180x180.png
    favicon_192: /favicon/dark/favicon-192x192.png
    favicon_512: /favicon/dark/favicon-512x512.png
  light:
    favicon: /favicon/light/favicon.ico
    icon: /favicon/light/favicon.svg
    favicon_16: /favicon/light/favicon-16x16.png
    favicon_32: /favicon/light/favicon-32x32.png
    favicon_180: /favicon/light/favicon-180x180.png
    favicon_192: /favicon/light/favicon-192x192.png
    favicon_512: /favicon/light/favicon-512x512.png
# è‡ªå®šä¹‰ meta æ ‡ç­¾
customMetas:
  # Google ç«™ç‚¹éªŒè¯
  - name: google-site-verification
    content: ZGzu_KLisGQkG8Fmz8fyZ8VvdtFQZyg7WqAYshcHlJY
  # ç™¾åº¦ ç«™ç‚¹éªŒè¯
  - name: baidu-site-verification
    content: codeva-3S13SuprEU
  # bing ç«™ç‚¹éªŒè¯
  - name: msvalidate.01
    content: D46176825688FA3D0C855598CDAB325F
# å…³é”®è¯
keywords:
  - Linlccc
  - Blog
  - PaperMod
# ç«™ç‚¹ä½œè€…
author:
  name: Linlccc
  email: linlccc@163.com

# logo ä¿¡æ¯
logo:
  text: linlccc's blog
  image: /favicon/dark/favicon-192x192.png
  imageHeight: 30

# éšè—é¡µè„š
hideFooter: false
# ç½‘ç«™å¼€å§‹ä½¿ç”¨å¹´ä»½
startYear: 2023
# æä¾›å•†ä¿¡æ¯
powereds:
  - name: Hugo
    url: https://gohugo.io/
  - name: PaperMod
    url: https://github.com/adityatelange/hugo-PaperMod/

# ç«™ç‚¹çš„ç‰¹æ®Š page é¡µï¼Œ(Kind == "page" && ä¸æ˜¯æ–‡ç« é¡µ)
specialPages:
  - search
  - archives

# åœ¨æ¡£æ¡ˆé¡µæ˜¾ç¤ºæ‰€æœ‰é¡µé¢
showAllPagesInArchive: true

### Home é¡µé…ç½® ###
# ç»å…¸æ¨¡å¼ä¿¡æ¯
classicInfo:
  # å¯ç”¨
  enabled: true
  # æ ‡é¢˜
  title: ä¸å¦‚æ‘¸é±¼ï¼ï¼
  # å†…å®¹
  content: ğŸ˜€ğŸ˜ƒğŸ˜„ğŸ˜ğŸ˜†ğŸ˜…ğŸ¤£ğŸ˜‚ğŸ™‚ğŸ™ƒğŸ˜‰ğŸ˜ŠğŸ˜‡ğŸ¥°ğŸ˜ğŸ¤©ğŸ˜˜ğŸ˜—ğŸ˜šğŸ˜™ğŸ˜‹ğŸ˜›ğŸ˜œğŸ¤ªğŸ˜ğŸ¤‘ğŸ¤—ğŸ¤­ğŸ¤«ğŸ¤”ğŸ¤ğŸ¤¨ğŸ˜ğŸ˜‘ğŸ˜¶ğŸ˜¶â€ğŸŒ«ï¸ğŸ˜ğŸ˜’ğŸ™„ğŸ˜¬ğŸ˜®â€ğŸ’¨ğŸ¤¥ğŸ˜ŒğŸ˜”ğŸ˜ªğŸ¤¤ğŸ˜´ğŸ˜·ğŸ¤’ğŸ¤•ğŸ¤¢ğŸ¤®ğŸ¤§ğŸ¥µğŸ¥¶ğŸ¥´ğŸ˜µğŸ˜µâ€ğŸ’«ğŸ¤¯ğŸ¤ ğŸ¥³ğŸ˜ğŸ¤“ğŸ§ğŸ˜•ğŸ˜ŸğŸ™â˜¹ï¸ğŸ˜®ğŸ˜¯ğŸ˜²ğŸ˜³ğŸ¥ºğŸ˜¦ğŸ˜§ğŸ˜¨ğŸ˜°ğŸ˜¥ğŸ˜¢ğŸ˜­ğŸ˜±ğŸ˜–ğŸ˜£ğŸ˜ğŸ˜“ğŸ˜©ğŸ˜«ğŸ¥±ğŸ˜¤ğŸ˜¡ğŸ˜ ğŸ¤¬ğŸ˜ˆğŸ‘¿ğŸ’€â˜ ï¸ğŸ’©ğŸ¤¡ğŸ‘¹ğŸ‘ºğŸ‘»ğŸ‘½ğŸ‘¾ğŸ¤–ğŸ˜ºğŸ˜¸ğŸ˜¹ğŸ˜»ğŸ˜¼ğŸ˜½ğŸ™€ğŸ˜¿ğŸ˜¾

# ç®€ä»‹æ¨¡å¼ä¿¡æ¯
profileInfo:
  # æ ‡é¢˜
  title: 00000000!!!
  # å†…å®¹
  content: ğŸ˜€ğŸ˜ƒğŸ˜„ğŸ˜ğŸ˜†ğŸ˜…ğŸ¤£ğŸ˜‚ğŸ™‚ğŸ™ƒğŸ˜‰ğŸ˜ŠğŸ˜‡ğŸ¥°ğŸ˜ğŸ¤©ğŸ˜˜ğŸ˜—ğŸ˜šğŸ˜™ğŸ˜‹ğŸ˜›ğŸ˜œğŸ¤ªğŸ˜ğŸ¤‘ğŸ¤—ğŸ¤­ğŸ¤«ğŸ¤”ğŸ¤ğŸ¤¨ğŸ˜ğŸ˜‘ğŸ˜¶ğŸ˜¶â€ğŸŒ«ï¸ğŸ˜ğŸ˜’ğŸ™„ğŸ˜¬ğŸ˜®â€ğŸ’¨ğŸ¤¥ğŸ˜ŒğŸ˜”ğŸ˜ªğŸ¤¤ğŸ˜´ğŸ˜·ğŸ¤’ğŸ¤•ğŸ¤¢ğŸ¤®ğŸ¤§ğŸ¥µğŸ¥¶ğŸ¥´ğŸ˜µğŸ˜µâ€ğŸ’«ğŸ¤¯ğŸ¤ ğŸ¥³ğŸ˜ğŸ¤“ğŸ§ğŸ˜•ğŸ˜ŸğŸ™â˜¹ï¸ğŸ˜®ğŸ˜¯ğŸ˜²ğŸ˜³ğŸ¥ºğŸ˜¦ğŸ˜§ğŸ˜¨ğŸ˜°ğŸ˜¥ğŸ˜¢ğŸ˜­ğŸ˜±ğŸ˜–ğŸ˜£ğŸ˜ğŸ˜“ğŸ˜©ğŸ˜«ğŸ¥±ğŸ˜¤ğŸ˜¡ğŸ˜ ğŸ¤¬ğŸ˜ˆğŸ‘¿ğŸ’€â˜ ï¸ğŸ’©ğŸ¤¡ğŸ‘¹ğŸ‘ºğŸ‘»ğŸ‘½ğŸ‘¾ğŸ¤–ğŸ˜ºğŸ˜¸ğŸ˜¹ğŸ˜»ğŸ˜¼ğŸ˜½ğŸ™€ğŸ˜¿ğŸ˜¾
  # å›¾ç‰‡
  image:
    url: /images/site/icon192.png
    title: LIN
    width: 120
    height: 120
  # æŒ‰é’®
  buttons:
    - name: Posts
      url: posts

# ç¤¾äº¤å›¾æ ‡
socialIcons:
  - name: github
    url: https://github.com/Linlccc
  - name: email
    url: mailto:linlcccc@gmail.com
  - name: rss
    url: index.xml

# Home é¡µæ˜¾ç¤ºçš„æ–‡ç« ç±»å‹(å†…å®¹æ–‡ç« ç›®å½•åæˆ–æ–‡ç« çš„ type é…ç½®)
homeShowTypes:
  - posts
  - games

### æ–‡ç« åˆ—è¡¨é…ç½® ###
# æ–‡ç« åˆ—è¡¨å’Œæ–‡ç« å¤´éƒ¨æ˜¾ç¤ºé¢åŒ…å±‘
listShowBreadCrumbs: true
# éšè—æ‘˜è¦
hideSummary: false

# å…ƒä¿¡æ¯(æ–‡ç« åˆ—è¡¨å’Œå†…å®¹é¡µç”¨åˆ°)
# éšè—å…ƒ
hidemeta: false
# æ—¥æœŸæ ¼å¼
dateFormat: 2006-01-02
# æ˜¾ç¤ºé˜…è¯»æ—¶é—´
showReadingTime: true
# æ˜¾ç¤ºå­—æ•°
showWordCount: true
# æ˜¾ç¤ºä½œè€…
showAuthor: true

# æ–‡ç« å°é¢
cover:
  # å›¾ç‰‡ç”Ÿæˆé“¾æ¥
  linkFullImages: true

### æœç´¢é¡µé¢é…ç½® ###
# fuseæœç´¢é…ç½® see:https://fusejs.io/api/options.html
fuseOptions:
  # åŒºåˆ†å¤§å°å†™
  isCaseSensitive: false
  # æ’åº
  shouldSort: true
  # ä½ç½®
  location: 0
  # è·ç¦»
  distance: 1000
  # é˜ˆå€¼,åŒ¹é…ç®—æ³•åœ¨ä»€ä¹ˆæ—¶å€™æ”¾å¼ƒåŒ¹é…,0-1ä¹‹é—´,è¶Šå°è¶Šä¸¥æ ¼
  threshold: 0.4
  # æœ€å°åŒ¹é…å­—ç¬¦é•¿åº¦
  minMatchCharLength: 0
  # åŒ¹é…é”®
  keys:
    - title
    - permalink
    - summary
    - content

### æ–‡ç« é¡µé…ç½® ###
# é¡µé¢æ˜¾ç¤ºé¢åŒ…å±‘å¯¼èˆª
showBreadCrumbs: true
# æ–‡ç« ç¼–è¾‘é“¾æ¥ä¿¡æ¯
editPost:
  # é“¾æ¥
  url: https://github.com/Linlccc/Linlccc.github.io/edit/master/src/content
  # å°†æ–‡ä»¶è·¯å¾„é™„åŠ åˆ°ç¼–è¾‘é“¾æ¥
  appendFilePath: true
  # ç¦ç”¨ç¼–è¾‘
  disabled: false

# æ˜¾ç¤ºåŸæ–‡ç« ä¿¡æ¯ï¼Œç”¨äºæ˜¾ç¤ºè½¬è½½è‡ªå“ªé‡Œ
showCanonicalLink: true

# æ˜¾ç¤ºç›®å½•
showToc: true
# ç›®å½•æ‰“å¼€
tocOpen: true

# æ˜¾ç¤ºå¸–å­å¯¼èˆªé“¾æ¥
showPostNavLinks: true

# ç¦ç”¨åˆ†äº«åŠŸèƒ½
disableShare: false
# æ˜¯å¦ä½¿ç”¨è‡ªå®šä¹‰åˆ†äº«æŒ‰é’®
customShare: true
# è‡ªå®šä¹‰åˆ†äº«æŒ‰é’®
customShareButtons:
  - x
  - linkedin
  - reddit
  - facebook
  - whatsapp
  - telegram
  - ycombinator

# giscus è¯„è®ºä¿¡æ¯, é…ç½® see:https://giscus.app/
giscusComments:
  enabled: true
  conf:
    data-repo: Linlccc/Linlccc.github.io
    data-repo-id: R_kgDOI9kokw
    data-category: Announcements
    data-category-id: DIC_kwDOI9kok84CUU3Q
    data-mapping: pathname
    data-strict: 1
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: bottom
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous

# ç¦ç”¨é”šå®šæ ‡é¢˜
disableAnchoredHeadings: false
### Hugo å†…ç½®æ¨¡æ¿é…ç½® ###
# å°†ç½‘ç«™å’Œä½ çš„ Twitter è´¦æˆ·å…³è”èµ·æ¥
social:
  twitter: Linlcccc

# ç«™ç‚¹å›¾åƒ
images:
  - /favicon/dark/favicon-192x192.png
