# å‚æ•°é…ç½®

# è¿™é‡Œæ˜¯çœŸæ­£ä¼šç”¨åˆ°çš„å‚æ•°ï¼Œå¯¹å‚æ•°é‡å†™
#################################

# æè¿°
description: ä¸å¦‚æ‘¸é±¼ï¼ï¼ï¼
# é»˜è®¤ä¸»é¢˜  [auto, dark, light]
defaultTheme: auto
# ç¦ç”¨ä¸»é¢˜åˆ‡æ¢
disableThemeToggle: false

# logo ä¿¡æ¯
logo:
  text: linlccc's blog
  image: /favicon/dark/favicon-192x192.png
  imageHeight: 30

# ç«™ç‚¹å›¾åƒ
images:
  - /favicon/dark/favicon-192x192.png

# æ˜¯å¦å¯ç”¨ manifest (å®‰è£…åˆ°æ¡Œé¢)
isEnableManifest: true
# å…³é”®è¯
keywords:
  - Linlccc
  - Blog
  - PaperMod
# ä½œè€…
authors:
  - Linlccc

# ä¸»é¢˜é¢œè‰²ï¼ˆåœ¨æ‰‹æœºæµè§ˆå™¨ä¸Šä¸‹ç©ºç™½åŒºåŸŸé¢œè‰²ï¼‰TODOï¼šè¿™é‡Œåé¢çœ‹æ€ä¹ˆæ”¹
theme_color:

# è‡ªå®šä¹‰ meta æ ‡ç­¾
customMetas:
  # Google ç«™ç‚¹éªŒè¯
  - name: google-site-verification
    content: ZGzu_KLisGQkG8Fmz8fyZ8VvdtFQZyg7WqAYshcHlJY
  # ç™¾åº¦ ç«™ç‚¹éªŒè¯
  - name: baidu-site-verification
    content: codeva-3S13SuprEU
  # bing ç«™ç‚¹éªŒè¯
  - name: msvalidate.01
    content: D46176825688FA3D0C855598CDAB325F

# æœç´¢é…ç½® see:https://fusejs.io/api/options.html
fuseOpts:
  # åŒºåˆ†å¤§å°å†™
  isCaseSensitive: false
  # æ’åº
  shouldSort: true
  # ä½ç½®
  location: 0
  # è·ç¦»
  distance: 1000
  # é˜ˆå€¼,åŒ¹é…ç®—æ³•åœ¨ä»€ä¹ˆæ—¶å€™æ”¾å¼ƒåŒ¹é…,0-1ä¹‹é—´,è¶Šå°è¶Šä¸¥æ ¼
  threshold: 0.4
  # æœ€å°åŒ¹é…å­—ç¬¦é•¿åº¦
  minMatchCharLength: 0
  # åŒ¹é…é”®
  keys:
    - title
    - permalink
    - summary
    - content

# hugo å†…ç½®æ¨¡æ¿é…ç½®ï¼Œç”¨æˆ·ç»‘å®šä½ çš„twirrerè´¦æˆ·
social:
  twitter: Linlcccc

# ç½‘ç«™å›¾æ ‡
favicon:
  dark:
    favicon: /favicon/dark/favicon.ico
    icon: /favicon/dark/favicon.svg
    favicon_16: /favicon/dark/favicon-16x16.png
    favicon_32: /favicon/dark/favicon-32x32.png
    favicon_180: /favicon/dark/favicon-180x180.png
    favicon_192: /favicon/dark/favicon-192x192.png
    favicon_512: /favicon/dark/favicon-512x512.png
  light:
    favicon: /favicon/light/favicon.ico
    icon: /favicon/light/favicon.svg
    favicon_16: /favicon/light/favicon-16x16.png
    favicon_32: /favicon/light/favicon-32x32.png
    favicon_180: /favicon/light/favicon-180x180.png
    favicon_192: /favicon/light/favicon-192x192.png
    favicon_512: /favicon/light/favicon-512x512.png

#################################

# ç¯å¢ƒå˜é‡[development, production]
# å¦‚æœè®¾ç½®æˆ productionï¼Œ åœ¨å¼€å‘æ—¶ä¼šæŒ‰ç…§ç”Ÿäº§ç¯å¢ƒåŠ è½½å†…å®¹
env: production

# ç¦ç”¨ç‰¹æ®Šçš„ç¬¬ä¸€ä¸ªå¸–å­(ä¸ç¦ç”¨ && params.homeInfoParams ä¹Ÿæ²¡æœ‰æ•°æ®æ—¶ï¼Œä¼šæŠŠç¬¬ä¸€ä¸ªå¸–å­å½“åšç½‘ç«™ä»‹ç»)
disableSpecial1stPost: true
# éšè—é¡µè„š
hideFooter: false
# åœ¨æ–‡æ¡£ä¹Ÿæ˜¾ç¤ºæ‰€æœ‰é¡µé¢
ShowAllPagesInArchive: true

# æ–‡ç« åˆ—è¡¨é…ç½®
# éšè—æ‘˜è¦ï¼ˆéšè—æ–‡ç« åˆ—è¡¨é¡µé¢çš„ä¸­çš„æ–‡ç« è¯¦æƒ…ï¼‰
hideSummary: false
# æ–‡ç« åˆ—è¡¨ä¸­æ˜¾ç¤º Rss æŒ‰é’®
ShowRssButtonInSectionTermList: true

# æ–‡ç« é…ç½®
# æ˜¾ç¤ºé¢åŒ…å±‘
ShowBreadCrumbs: false
# å…ƒä¿¡æ¯
# éšè—å…ƒ(å†…å®¹/åˆ—è¡¨ç­‰é¡µé¢ï¼Œç”¨äºå‘ˆç°å†…å®¹ä¿¡æ¯)
hidemeta: false
# æ—¥æœŸæ ¼å¼
DateFormat: 2006-01-02
# æ˜¾ç¤ºé˜…è¯»æ—¶é—´
ShowReadingTime: true
# æ˜¾ç¤ºå­—æ•°
ShowWordCount: true
# éšè—ä½œè€…
HideAuthor: false

# åŸæ–‡ç« æ¥è‡ªå“ªé‡Œçš„æç¤ºæ–‡ç« 
CanonicalLinkText: è½¬è½½è‡ª
# æ˜¾ç¤ºåŸæ–‡ç« é“¾æ¥
ShowCanonicalLink: true
# ç›®å½•
# æ˜¾ç¤ºç›®å½•
showtoc: true
# ç›®å½•æ‰“å¼€
tocopen: true
# ä½¿ç”¨Hugoç›®å½•(ä½¿ç”¨hugoç›®å½•å°±å¯ä»¥ä½¿ç”¨ tableOfContents é…ç½®)
UseHugoToc: true
# å†…å®¹
# æ˜¾ç¤ºä»£ç å¤åˆ¶æŒ‰é’®
ShowCodeCopyButtons: true
# æ˜¾ç¤ºå¸–å­å¯¼èˆªé“¾æ¥
ShowPostNavLinks: true
# æ˜¾ç¤ºåˆ†äº«æŒ‰é’®
ShowShareButtons: true
# ç¦ç”¨æ»šåŠ¨åˆ°é¡¶éƒ¨
disableScrollToTop: false
# è¯„è®º
comments: true

# è‡ªå·±çš„ä¸€äº›é…ç½®
# ç½‘ç«™å¼€å§‹ä½¿ç”¨æ—¶é—´
StartYear: 2023

# ä¸»é¡µæ˜¯ä¸ªäººé¡µé¢
profileMode:
  # å¯ç”¨
  enabled: false
  # æ ‡é¢˜
  title: ä¸å¦‚æ‘¸é±¼ï¼ï¼
  # å­—å¹•
  subtitle: ğŸ˜€ğŸ˜ƒğŸ˜„ğŸ˜ğŸ˜†ğŸ˜…ğŸ¤£ğŸ˜‚ğŸ™‚ğŸ™ƒğŸ˜‰ğŸ˜ŠğŸ˜‡ğŸ¥°ğŸ˜ğŸ¤©ğŸ˜˜ğŸ˜—ğŸ˜šğŸ˜™ğŸ˜‹ğŸ˜›ğŸ˜œğŸ¤ªğŸ˜ğŸ¤‘ğŸ¤—ğŸ¤­ğŸ¤«ğŸ¤”ğŸ¤ğŸ¤¨ğŸ˜ğŸ˜‘ğŸ˜¶ğŸ˜¶â€ğŸŒ«ï¸ğŸ˜ğŸ˜’ğŸ™„ğŸ˜¬ğŸ˜®â€ğŸ’¨ğŸ¤¥ğŸ˜ŒğŸ˜”ğŸ˜ªğŸ¤¤ğŸ˜´ğŸ˜·ğŸ¤’ğŸ¤•ğŸ¤¢ğŸ¤®ğŸ¤§ğŸ¥µğŸ¥¶ğŸ¥´ğŸ˜µğŸ˜µâ€ğŸ’«ğŸ¤¯ğŸ¤ ğŸ¥³ğŸ˜ğŸ¤“ğŸ§ğŸ˜•ğŸ˜ŸğŸ™â˜¹ï¸ğŸ˜®ğŸ˜¯ğŸ˜²ğŸ˜³ğŸ¥ºğŸ˜¦ğŸ˜§ğŸ˜¨ğŸ˜°ğŸ˜¥ğŸ˜¢ğŸ˜­ğŸ˜±ğŸ˜–ğŸ˜£ğŸ˜ğŸ˜“ğŸ˜©ğŸ˜«ğŸ¥±ğŸ˜¤ğŸ˜¡ğŸ˜ ğŸ¤¬ğŸ˜ˆğŸ‘¿ğŸ’€â˜ ï¸ğŸ’©ğŸ¤¡ğŸ‘¹ğŸ‘ºğŸ‘»ğŸ‘½ğŸ‘¾ğŸ¤–ğŸ˜ºğŸ˜¸ğŸ˜¹ğŸ˜»ğŸ˜¼ğŸ˜½ğŸ™€ğŸ˜¿ğŸ˜¾
  # å›¾åƒ
  imageUrl: /images/site/icon192.png
  # å›¾åƒå®½é«˜
  imageWidth: 120
  imageHeight: 120
  # å›¾ç‰‡æ ‡é¢˜
  imageTitle: Linlccc
  buttons:
    # ä¸ªäººé¡µé¢æŒ‰é’®
    - name: Posts
      url: posts
    - name: Tags
      url: tags

# æ™®é€šä¸»é¡µä¸ªäººä¿¡æ¯
homeInfoParams:
  # æ ‡é¢˜
  Title: ä¸å¦‚æ‘¸é±¼ï¼ï¼
  # å†…å®¹
  Content: ğŸ˜€ğŸ˜ƒğŸ˜„ğŸ˜ğŸ˜†ğŸ˜…ğŸ¤£ğŸ˜‚ğŸ™‚ğŸ™ƒğŸ˜‰ğŸ˜ŠğŸ˜‡ğŸ¥°ğŸ˜ğŸ¤©ğŸ˜˜ğŸ˜—ğŸ˜šğŸ˜™ğŸ˜‹ğŸ˜›ğŸ˜œğŸ¤ªğŸ˜ğŸ¤‘ğŸ¤—ğŸ¤­ğŸ¤«ğŸ¤”ğŸ¤ğŸ¤¨ğŸ˜ğŸ˜‘ğŸ˜¶ğŸ˜¶â€ğŸŒ«ï¸ğŸ˜ğŸ˜’ğŸ™„ğŸ˜¬ğŸ˜®â€ğŸ’¨ğŸ¤¥ğŸ˜ŒğŸ˜”ğŸ˜ªğŸ¤¤ğŸ˜´ğŸ˜·ğŸ¤’ğŸ¤•ğŸ¤¢ğŸ¤®ğŸ¤§ğŸ¥µğŸ¥¶ğŸ¥´ğŸ˜µğŸ˜µâ€ğŸ’«ğŸ¤¯ğŸ¤ ğŸ¥³ğŸ˜ğŸ¤“ğŸ§ğŸ˜•ğŸ˜ŸğŸ™â˜¹ï¸ğŸ˜®ğŸ˜¯ğŸ˜²ğŸ˜³ğŸ¥ºğŸ˜¦ğŸ˜§ğŸ˜¨ğŸ˜°ğŸ˜¥ğŸ˜¢ğŸ˜­ğŸ˜±ğŸ˜–ğŸ˜£ğŸ˜ğŸ˜“ğŸ˜©ğŸ˜«ğŸ¥±ğŸ˜¤ğŸ˜¡ğŸ˜ ğŸ¤¬ğŸ˜ˆğŸ‘¿ğŸ’€â˜ ï¸ğŸ’©ğŸ¤¡ğŸ‘¹ğŸ‘ºğŸ‘»ğŸ‘½ğŸ‘¾ğŸ¤–ğŸ˜ºğŸ˜¸ğŸ˜¹ğŸ˜»ğŸ˜¼ğŸ˜½ğŸ™€ğŸ˜¿ğŸ˜¾

# ç¤¾äº¤å›¾æ ‡
socialIcons:
  - name: github
    url: https://github.com/Linlccc
  - name: email
    url: mailto:linlcccc@gmail.com
  - name: rss
    url: /index.xml

# æ–‡ç« å°é¢
cover:
  # éšè—å°é¢
  hidden: false
  # åœ¨æ–‡ç« å†…å®¹é¡µé¢éšè—å°é¢  ä¼˜å…ˆçº§ Page.Param.cover.hidden > Site.Param.cover.hiddenInSingle > Site.Param.cover.hidden
  hiddenInSingle: true
  # åœ¨æ–‡ç« åˆ—è¡¨ä¸­éšè—å°é¢ ä¼˜å…ˆçº§ Site.Param.cover.hiddenInList > Site.Param.cover.hidden
  hiddenInList: false
  # å“åº”å¼å›¾ç‰‡
  responsiveImages: true
  # å›¾ç‰‡ç”Ÿæˆé“¾æ¥
  linkFullImages: true

# æ–‡ç« ç¼–è¾‘é“¾æ¥ä¿¡æ¯
editPost:
  # é“¾æ¥
  URL: https://github.com/Linlccc/Linlccc.github.io/edit/master/src/content
  # ç¼–è¾‘æ–‡æœ¬
  Text: ç¼–è¾‘
  # å°†æ–‡ä»¶è·¯å¾„é™„åŠ åˆ°ç¼–è¾‘é“¾æ¥
  appendFilePath: true
  # ç¦ç”¨ç¼–è¾‘
  disabled: false

# è®¾ç½®åœ¨ä¸»é¡µæ˜¾ç¤ºçš„æ–‡ç« ç±»å‹(è®¾ç½®å†…å®¹ä¸ºcontentç›®å½•ä¸‹çš„ç›®å½•å)
mainSections:
  - blog
  - posts
  - games
