##########################################
# è¯¥é…ç½®æ–‡ä»¶ä¸»è¦ç”¨äºé…ç½®ä¸»é¢˜å’Œè‡ªå·±çš„ä¸€äº›é…ç½® #
##########################################
theme = 'PaperMod'

# å‚æ•°
[Params]
  # ç«™ç‚¹é…ç½®
  # ç”Ÿäº§ç¯å¢ƒæ—¶å¯ç”¨ google analyticsã€opengraphã€twitter-cards å’Œ schemaã€‚
  env = 'production'
  # æ ‡é¢˜
  title = "Linlccc's Blog"
  # æè¿°
  description = "ä¸å¦‚æ‘¸é±¼ï¼ï¼ï¼"
  # å…³é”®è¯
  keywords = ['Linlccc','Blog', 'PaperMod']
  # å›¾åƒ
  images = ['/images/site/icon192.png']
  # é»˜è®¤ä¸»é¢˜  [auto, dark, light]
  defaultTheme = 'auto'
  # ç¦ç”¨ä¸»é¢˜åˆ‡æ¢
  disableThemeToggle = false
  # ç¦ç”¨ç‰¹æ®Šçš„ç¬¬ä¸€ä¸ªå¸–å­(ä¸ç¦ç”¨ && params.homeInfoParams ä¹Ÿæ²¡æœ‰æ•°æ®æ—¶ï¼Œä¼šæŠŠç¬¬ä¸€ä¸ªå¸–å­å½“åšç½‘ç«™ä»‹ç»)
  disableSpecial1stPost = true
  # éšè—é¡µè„š
  hideFooter = false
  # åœ¨æ–‡æ¡£ä¹Ÿæ˜¾ç¤ºæ‰€æœ‰é¡µé¢
  ShowAllPagesInArchive = true
  # æ˜¯å¦å¯ç”¨ manifest (å®‰è£…åˆ°æ¡Œé¢)
  IsEnableManifest = true

  # æ–‡ç« åˆ—è¡¨é…ç½®
  # éšè—æ‘˜è¦ï¼ˆéšè—æ–‡ç« åˆ—è¡¨é¡µé¢çš„ä¸­çš„æ–‡ç« è¯¦æƒ…ï¼‰
  hideSummary = false
  # æ–‡ç« åˆ—è¡¨ä¸­æ˜¾ç¤º Rss æŒ‰é’®
  ShowRssButtonInSectionTermList = true

  # æ–‡ç« é…ç½®
  # æ˜¾ç¤ºé¢åŒ…å±‘
  ShowBreadCrumbs = false
  # å…ƒä¿¡æ¯
  # éšè—å…ƒ(å†…å®¹/åˆ—è¡¨ç­‰é¡µé¢ï¼Œç”¨äºå‘ˆç°å†…å®¹ä¿¡æ¯)
  hidemeta = false
  # æ—¥æœŸæ ¼å¼
  DateFormat = "2006-01-02"
  # æ˜¾ç¤ºé˜…è¯»æ—¶é—´
  ShowReadingTime = true
  # æ˜¾ç¤ºå­—æ•°
  ShowWordCount = true
  # éšè—ä½œè€…
  HideAuthor = false
  # ä½œè€…
  author = ['Linlccc']
  # åŸæ–‡ç« æ¥è‡ªå“ªé‡Œçš„æç¤ºæ–‡ç« 
  CanonicalLinkText = 'è½¬è½½è‡ª'
  # ç›®å½•
  # æ˜¾ç¤ºç›®å½•
  showtoc = true
  # ç›®å½•æ‰“å¼€
  tocopen = true
  # ä½¿ç”¨Hugoç›®å½•(ä½¿ç”¨hugoç›®å½•å°±å¯ä»¥ä½¿ç”¨ tableOfContents é…ç½®)
  UseHugoToc = true
  # å†…å®¹
  # æ˜¾ç¤ºä»£ç å¤åˆ¶æŒ‰é’®
  ShowCodeCopyButtons = true
  # æ˜¾ç¤ºå¸–å­å¯¼èˆªé“¾æ¥
  ShowPostNavLinks = true
  # æ˜¾ç¤ºåˆ†äº«æŒ‰é’®
  ShowShareButtons = true
  # ç¦ç”¨æ»šåŠ¨åˆ°é¡¶éƒ¨
  disableScrollToTop = false
  # è¯„è®º
  comments = true

  ## è‡ªå·±çš„ä¸€äº›é…ç½®
  # ç½‘ç«™å¼€å§‹ä½¿ç”¨æ—¶é—´
  StartYear = 2023

  # èµ„äº§
  [Params.assets]
    # ç¦ç”¨ä»£ç é«˜äº®
    disableHLJS = false
    # ç¦ç”¨èµ„æºçš„å®Œæ•´æ€§ï¼ˆç”¨äºæ£€æŸ¥èµ„æºæ˜¯å¦è¢«ç¯¡æ”¹ï¼‰
    disableFingerprinting = false
    # ç¦ç”¨æ»šåŠ¨æ¡æ ·å¼
    disableScrollBarStyle = false
    # å›¾æ ‡
    favicon = '/images/site/icon192.png'
    favicon16x16 = "/images/site/icon16.png"
    favicon32x32 = "/images/site/icon32.png"
    # è‹¹æœè§¦æ‘¸å›¾æ ‡
    apple_touch_icon = "/images/site/icon192.png"
    # safari å›ºå®šæ ‡ç­¾
    safari_pinned_tab = "/images/site/icon192.png"
    # ä¸»é¢˜é¢œè‰²ï¼ˆåœ¨æ‰‹æœºæµè§ˆå™¨ä¸Šä¸‹ç©ºç™½åŒºåŸŸé¢œè‰²ï¼‰
    theme_color = ""

  # æ ‡ç­¾ï¼Œè¿›å…¥ä¸»é¡µçš„titleè®¾ç½®
  [Params.label]
    # æ–‡æœ¬
    text = ""
    # å›¾æ ‡
    icon = ''
    # å›¾æ ‡é«˜åº¦
    iconHeight = 35
    # text = "æµ‹è¯•"
    # icon = "/images/site/icon192.png"
    # icon = "https://linlccc.com/images/posts/test/test_post_1.png"
    # iconSVG = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -2 25 28" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">  <path style="font-variation-settings:normal"  d="M6.361 2.943 0 21.056h4.942l1.077-3.133H11.4l1.052 3.133H22.9c.71 0 1.1-.392 1.1-1.101V17.53c0-.71-.39-1.101-1.1-1.101h-6.483V4.045c0-.71-.392-1.102-1.101-1.102h-2.422c-.71 0-1.101.392-1.101 1.102v1.064l-.758-2.166zm2.324 5.948 1.688 5.018H7.144z" /></svg>'
    # iconHeight = 145

  # ä¸»é¡µæ˜¯ä¸ªäººé¡µé¢
  [Params.profileMode]
    # å¯ç”¨
    enabled = false
    # æ ‡é¢˜
    title = 'ä¸å¦‚æ‘¸é±¼ï¼ï¼'
    # å­—å¹•
    subtitle = "ğŸ˜€ğŸ˜ƒğŸ˜„ğŸ˜ğŸ˜†ğŸ˜…ğŸ¤£ğŸ˜‚ğŸ™‚ğŸ™ƒğŸ˜‰ğŸ˜ŠğŸ˜‡ğŸ¥°ğŸ˜ğŸ¤©ğŸ˜˜ğŸ˜—ğŸ˜šğŸ˜™ğŸ˜‹ğŸ˜›ğŸ˜œğŸ¤ªğŸ˜ğŸ¤‘ğŸ¤—ğŸ¤­ğŸ¤«ğŸ¤”ğŸ¤ğŸ¤¨ğŸ˜ğŸ˜‘ğŸ˜¶ğŸ˜¶â€ğŸŒ«ï¸ğŸ˜ğŸ˜’ğŸ™„ğŸ˜¬ğŸ˜®â€ğŸ’¨ğŸ¤¥ğŸ˜ŒğŸ˜”ğŸ˜ªğŸ¤¤ğŸ˜´ğŸ˜·ğŸ¤’ğŸ¤•ğŸ¤¢ğŸ¤®ğŸ¤§ğŸ¥µğŸ¥¶ğŸ¥´ğŸ˜µğŸ˜µâ€ğŸ’«ğŸ¤¯ğŸ¤ ğŸ¥³ğŸ˜ğŸ¤“ğŸ§ğŸ˜•ğŸ˜ŸğŸ™â˜¹ï¸ğŸ˜®ğŸ˜¯ğŸ˜²ğŸ˜³ğŸ¥ºğŸ˜¦ğŸ˜§ğŸ˜¨ğŸ˜°ğŸ˜¥ğŸ˜¢ğŸ˜­ğŸ˜±ğŸ˜–ğŸ˜£ğŸ˜ğŸ˜“ğŸ˜©ğŸ˜«ğŸ¥±ğŸ˜¤ğŸ˜¡ğŸ˜ ğŸ¤¬ğŸ˜ˆğŸ‘¿ğŸ’€â˜ ï¸ğŸ’©ğŸ¤¡ğŸ‘¹ğŸ‘ºğŸ‘»ğŸ‘½ğŸ‘¾ğŸ¤–ğŸ˜ºğŸ˜¸ğŸ˜¹ğŸ˜»ğŸ˜¼ğŸ˜½ğŸ™€ğŸ˜¿ğŸ˜¾"
    # å›¾åƒ
    imageUrl = "/images/site/icon192.png"
    # å›¾åƒå®½é«˜
    imageWidth = 120
    imageHeight = 120
    # å›¾ç‰‡æ ‡é¢˜
    imageTitle = 'Linlccc'

    # ä¸ªäººé¡µé¢æŒ‰é’®
    [[Params.profileMode.buttons]]
      name = 'Posts'
      url = 'posts'
    [[Params.profileMode.buttons]]
      name = 'Tags'
      url = 'tags'

  # æ™®é€šä¸»é¡µä¸ªäººä¿¡æ¯
  [Params.homeInfoParams]
    # æ ‡é¢˜
    Title = "ä¸å¦‚æ‘¸é±¼ï¼ï¼"
    # å†…å®¹
    Content = "ğŸ˜€ğŸ˜ƒğŸ˜„ğŸ˜ğŸ˜†ğŸ˜…ğŸ¤£ğŸ˜‚ğŸ™‚ğŸ™ƒğŸ˜‰ğŸ˜ŠğŸ˜‡ğŸ¥°ğŸ˜ğŸ¤©ğŸ˜˜ğŸ˜—ğŸ˜šğŸ˜™ğŸ˜‹ğŸ˜›ğŸ˜œğŸ¤ªğŸ˜ğŸ¤‘ğŸ¤—ğŸ¤­ğŸ¤«ğŸ¤”ğŸ¤ğŸ¤¨ğŸ˜ğŸ˜‘ğŸ˜¶ğŸ˜¶â€ğŸŒ«ï¸ğŸ˜ğŸ˜’ğŸ™„ğŸ˜¬ğŸ˜®â€ğŸ’¨ğŸ¤¥ğŸ˜ŒğŸ˜”ğŸ˜ªğŸ¤¤ğŸ˜´ğŸ˜·ğŸ¤’ğŸ¤•ğŸ¤¢ğŸ¤®ğŸ¤§ğŸ¥µğŸ¥¶ğŸ¥´ğŸ˜µğŸ˜µâ€ğŸ’«ğŸ¤¯ğŸ¤ ğŸ¥³ğŸ˜ğŸ¤“ğŸ§ğŸ˜•ğŸ˜ŸğŸ™â˜¹ï¸ğŸ˜®ğŸ˜¯ğŸ˜²ğŸ˜³ğŸ¥ºğŸ˜¦ğŸ˜§ğŸ˜¨ğŸ˜°ğŸ˜¥ğŸ˜¢ğŸ˜­ğŸ˜±ğŸ˜–ğŸ˜£ğŸ˜ğŸ˜“ğŸ˜©ğŸ˜«ğŸ¥±ğŸ˜¤ğŸ˜¡ğŸ˜ ğŸ¤¬ğŸ˜ˆğŸ‘¿ğŸ’€â˜ ï¸ğŸ’©ğŸ¤¡ğŸ‘¹ğŸ‘ºğŸ‘»ğŸ‘½ğŸ‘¾ğŸ¤–ğŸ˜ºğŸ˜¸ğŸ˜¹ğŸ˜»ğŸ˜¼ğŸ˜½ğŸ™€ğŸ˜¿ğŸ˜¾"

  # ç¤¾äº¤å›¾æ ‡
  # [[Params.socialIcons]]
  #   name = 'twitter'
  #   url = 'https://twitter.com/Linlccc'
  [[Params.socialIcons]]
    name = 'github'
    url = 'https://github.com/Linlccc'
  [[Params.socialIcons]]
    name = 'email'
    url = 'mailto:linlcccc@gmail.com'

  # æ–‡ç« å°é¢
  [Params.cover]
    # éšè—å°é¢
    hidden = false
    # åœ¨æ–‡ç« å†…å®¹é¡µé¢éšè—å°é¢  ä¼˜å…ˆçº§ Page.Param.cover.hidden > Site.Param.cover.hiddenInSingle > Site.Param.cover.hidden
    hiddenInSingle = false
    # åœ¨æ–‡ç« åˆ—è¡¨ä¸­éšè—å°é¢ ä¼˜å…ˆçº§ Site.Param.cover.hiddenInList > Site.Param.cover.hidden
    hiddenInList = false
    # å“åº”å¼å›¾ç‰‡
    responsiveImages= true
    # å›¾ç‰‡ç”Ÿæˆé“¾æ¥
    linkFullImages = true

  # æ–‡ç« ç¼–è¾‘é“¾æ¥ä¿¡æ¯
  [Params.editPost]
    # é“¾æ¥
    URL = "https://github.com/Linlccc/Linlccc.github.io/edit/master/src/content"
    # ç¼–è¾‘æ–‡æœ¬
    Text = "ç¼–è¾‘"
    # å°†æ–‡ä»¶è·¯å¾„é™„åŠ åˆ°ç¼–è¾‘é“¾æ¥
    appendFilePath = true
    # ç¦ç”¨ç¼–è¾‘
    disabled = false

  # Google ç«™ç‚¹éªŒè¯ meta æ ‡ç­¾ä¿¡æ¯
  [[Params.meta]]
    name = 'google-site-verification'
    content = 'ZGzu_KLisGQkG8Fmz8fyZ8VvdtFQZyg7WqAYshcHlJY'
    # ç™¾åº¦ ç«™ç‚¹éªŒè¯ meta æ ‡ç­¾ä¿¡æ¯
  [[Params.meta]]
    name = 'baidu-site-verification'
    content = 'codeva-3S13SuprEU'
  # bing ç«™ç‚¹éªŒè¯ meta æ ‡ç­¾ä¿¡æ¯
  [[Params.meta]]
    name = 'msvalidate.01'
    content = 'D46176825688FA3D0C855598CDAB325F'
  # yandex ç«™ç‚¹éªŒè¯ meta æ ‡ç­¾ä¿¡æ¯
  # [[Params.meta]]
  #   name = 'yandex-verification'
  #   content = 'yandex'
  # naver ç«™ç‚¹éªŒè¯ meta æ ‡ç­¾ä¿¡æ¯
  # [[Params.meta]]
  #   name = 'naver-site-verification'
  #   content = 'naver'

  # æœç´¢é…ç½® see:https://fusejs.io/api/options.html
  [Params.fuseOpts]
    # åŒºåˆ†å¤§å°å†™
    isCaseSensitive = false
    # æ’åº
    shouldSort = true
    # ä½ç½®
    location = 0
    # è·ç¦»
    distance = 1000
    # é˜ˆå€¼,åŒ¹é…ç®—æ³•åœ¨ä»€ä¹ˆæ—¶å€™æ”¾å¼ƒåŒ¹é…,0-1ä¹‹é—´,è¶Šå°è¶Šä¸¥æ ¼
    threshold = 0.4
    # æœ€å°åŒ¹é…å­—ç¬¦é•¿åº¦
    minMatchCharLength = 0
    # åŒ¹é…é”®
    keys = ["title", "permalink", "summary", "content"]

# æœç´¢è®¾ç½®
[outputs]
  home = [ "HTML", "RSS", "JSON" ]
