############################
# è¯¥é…ç½®æ–‡ä»¶ä¸»è¦ç”¨äºé…ç½®ä¸»é¢˜ #
############################
theme = 'PaperMod'


# å‚æ•°
[params]
  # ç«™ç‚¹é…ç½®
  # é»˜è®¤ä¸»é¢˜  [auto, dark, light]
  defaultTheme = 'auto'
  # ç¦ç”¨ä¸»é¢˜åˆ‡æ¢
  disableThemeToggle = false
  # ç¦ç”¨ç‰¹æ®Šçš„ç¬¬ä¸€ä¸ªå¸–å­(ä¸ç¦ç”¨ç¬¬ä¸€ä¸ªå¸–å­åœ¨ä¸»é¡µæ ·å¼å°±ä¸ä¸€æ ·)
  disableSpecial1stPost = true

  # æ–‡ç« é…ç½®
  # æ˜¾ç¤ºé¢åŒ…å±‘
  ShowBreadCrumbs = true
  # å…ƒä¿¡æ¯
  # éšè—å…ƒ
  hidemeta = false
  # æ—¥æœŸæ ¼å¼
  DateFormat = "2006-01-02"
  # æ˜¾ç¤ºé˜…è¯»æ—¶é—´
  ShowReadingTime = true
  # æ˜¾ç¤ºå­—æ•°
  ShowWordCount = true
  # ä½œè€…
  author = 'Linlccc'
  # ç›®å½•
  # æ˜¾ç¤ºç›®å½•
  showtoc = true
  # ç›®å½•æ‰“å¼€
  tocopen = false
  # ä½¿ç”¨Hugoç›®å½•(ä½¿ç”¨hugoç›®å½•å°±å¯ä»¥ä½¿ç”¨ tableOfContents é…ç½®)
  UseHugoToc = true
  # å†…å®¹
  # æ˜¾ç¤ºä»£ç å¤åˆ¶æŒ‰é’®
  ShowCodeCopyButtons = true
  # æ˜¾ç¤ºå¸–å­å¯¼èˆªé“¾æ¥
  ShowPostNavLinks = true
  # æ˜¾ç¤ºåˆ†äº«æŒ‰é’®
  ShowShareButtons = true
  # ç¦ç”¨æ»šåŠ¨åˆ°é¡¶éƒ¨
  disableScrollToTop = false
  # ä¸‹é¢æ²¡å‘ç°ä½œç”¨
  # è¯„è®º
  comments = true
  # éšè—æ€»ç»“
  hideSummary = false
  # ç”Ÿäº§ç¯å¢ƒæ—¶å¯ç”¨ google analyticsã€opengraphã€twitter-cards å’Œ schemaã€‚
  env = 'dev'
  # æ ‡é¢˜
  title = 'ExampleSite'
  # æè¿°
  description = "ExampleSite description"
  # å…³é”®è¯
  keywords = ['Blog', 'Portfolio', 'PaperMod']
  # å›¾åƒ
  images = ['/images/image_12.png']
  # åœ¨éƒ¨åˆ†æœ¯è¯­åˆ—è¡¨ä¸­æ˜¾ç¤º Rss æŒ‰é’®
  ShowRssButtonInSectionTermList = true

  # èµ„äº§
  [params.assets]
    # ç¦ç”¨ä»£ç é«˜äº®
    disableHLJS = false
    # ç¦ç”¨æŒ‡çº¹è¯†åˆ«
    disableFingerprinting = true
    # å›¾æ ‡
    favicon = '/images/image_12.png'
    favicon16x16 = "<link / abs url>"
    favicon32x32 = "<link / abs url>"
    # è‹¹æœè§¦æ‘¸å›¾æ ‡
    apple_touch_icon = "/images/image_12.png"
    # safari å›ºå®šæ ‡ç­¾
    safari_pinned_tab = "/images/image_12.png"

  # æ ‡ç­¾ï¼Œè¿›å…¥ä¸»é¡µçš„titleè®¾ç½®
  [params.label]
    # æ–‡æœ¬
    text = "Home"
    # å›¾æ ‡
    icon = '/images/image_12.png'
    # å›¾æ ‡é«˜åº¦
    iconHeight = 35

  # ä¸»é¡µæ˜¯ä¸ªäººé¡µé¢
  [params.profileMode]
    # å¯ç”¨
    enabled = false
    # æ ‡é¢˜
    title = 'Linlccc'
    # å­—å¹•
    subtitle = "Hello World!!!!!"
    # å›¾åƒ
    imageUrl = "/images/image_12.png"
    # å›¾åƒå®½é«˜
    imageWidth = 120
    imageHeight = 120
    # å›¾ç‰‡æ ‡é¢˜
    imageTitle = 'my image'

    # ä¸ªäººé¡µé¢æŒ‰é’®
    [[params.profileMode.buttons]]
      name = 'Posts'
      url = 'posts'
    [[params.profileMode.buttons]]
      name = 'Tags'
      url = 'tags'

  # æ™®é€šä¸»é¡µä¸ªäººä¿¡æ¯
  [params.homeInfoParams]
    # æ ‡é¢˜
    Title = "Hi there ğŸ‘‹ \U0001F44B"
    # å†…å®¹
    Content = "Welcome to demo of hugoâ€™s theme PaperMod.PaperMod is a simple but fast and responsive theme with useful feature-set that enhances UX.Do give a ğŸŒŸ on Github !PaperMod is based on theme Paper.Welcome to demo of hugoâ€™s theme Paper"

  # ç¤¾äº¤å›¾æ ‡
  [[params.socialIcons]]
    name = 'twitter'
    url = 'https://twitter.com/'
  [[params.socialIcons]]
    name = 'stackoverflow'
    url = 'https://stackoverflow.com/'
  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/'

  # åˆ†æ
  # [params.analytics.google]
  #   SiteVerificationTag = "G-TQ3ZXPKKNM"
  # [params.analytics.bing]
  #   SiteVerificationTag = "xxxxx"
  # [params.analytics.yandex]
  #   SiteVerificationTag = "xxxxx"

  # æ–‡ç« å°é¢(è¿™ä¸ªå®Œå…¨æ²¡ææ‡‚)
  [params.cover]
    # éšè—å°é¢å›¾ç‰‡
    hidden = false
    # ä¹Ÿæ˜¯éšè—å°é¢å›¾ç‰‡
    hiddenInList = false
    # éšè—åœ¨å•ä¸ªé¡µé¢ä¸Š
    hiddenInSingle = false

  # æ–‡ç« ç¼–è¾‘é“¾æ¥ä¿¡æ¯
  [params.editPost]
    # é“¾æ¥
    URL = "https://github.com/Linlccc/Linlccc.github.io/content"
    # ç¼–è¾‘æ–‡æœ¬
    Text = "edit"
    # å°†æ–‡ä»¶è·¯å¾„é™„åŠ åˆ°ç¼–è¾‘é“¾æ¥
    appendFilePath = true

  # æœç´¢ https://fusejs.io/api/options.html
  [params.fuseOpts]
    # åŒºåˆ†å¤§å°å†™
    isCaseSensitive = false
    # æ’åº
    shouldSort = true
    # ä½ç½®
    location = 0
    # è·ç¦»
    distance = 1000
    # é˜ˆå€¼
    threshold = 0.4
    # æœ€å°åŒ¹é…å­—ç¬¦é•¿åº¦
    minMatchCharLength = 0
    # åŒ¹é…é”®
    keys = ["title", "permalink", "summary", "content"]
